log_format upstream_json escape=json
    '{'
    '"time":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"request":"$request",'
    '"status":$status,'
    '"body_bytes_sent":$body_bytes_sent,'
    '"request_time":$request_time,'
    '"upstream_addr":"$upstream_addr",'
    '"upstream_status":"$upstream_status",'
    '"upstream_response_time":"$upstream_response_time",'
    '"host":"$http_host",'
    '"user_agent":"$http_user_agent"'
    '}';

limit_req_zone $binary_remote_addr zone=api_limit:10m rate=2r/s;

resolver 127.0.0.11 valid=5s ipv6=off;

server {
    listen 80;

    return 301 https://$host:8443$request_uri;
}

server {
    listen 443 ssl;

    access_log /var/log/nginx/access.log upstream_json;

    ssl_certificate /etc/nginx/certs/devops.local.crt;
    ssl_certificate_key /etc/nginx/certs/devops.local.key;

    client_max_body_size 10m;

    location = /health {
        default_type text/plain;
        return 200 "nginx is alive over https\n";
    }

    location /static/ {
        alias /usr/share/nginx/static/;
        index index.html;
    }

    location = /api {
        return 301 /api/;
    }

    location /api/ {
        limit_req zone=api_limit burst=3 nodelay;
        limit_req_status 429;

        set $backend http://app-green:3000;
        proxy_pass $backend;

        proxy_connect_timeout 3s;
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        default_type text/plain;
        return 404 "not found\n";
    }
}
